//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.24 at 05:43:19 PM CEST 
//


package de.steri.springbatch.xml.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FooterType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FooterType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="anzahlDatensätze" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="erstellungsdatum" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FooterType", propOrder = {
    "anzahlDatens\u00e4tze",
    "erstellungsdatum"
})
public class FooterType {

    protected int anzahlDatensätze;
    @XmlElement(required = true)
    protected String erstellungsdatum;

    /**
     * Gets the value of the anzahlDatensätze property.
     * 
     */
    public int getAnzahlDatensätze() {
        return anzahlDatensätze;
    }

    /**
     * Sets the value of the anzahlDatensätze property.
     * 
     */
    public void setAnzahlDatensätze(int value) {
        this.anzahlDatensätze = value;
    }

    /**
     * Gets the value of the erstellungsdatum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getErstellungsdatum() {
        return erstellungsdatum;
    }

    /**
     * Sets the value of the erstellungsdatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setErstellungsdatum(String value) {
        this.erstellungsdatum = value;
    }

}
