//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.24 at 05:43:19 PM CEST 
//


package de.steri.springbatch.xml.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HeaderType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HeaderType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EmpfängerID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="EmpfängerName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HeaderType", propOrder = {
    "empf\u00e4ngerID",
    "empf\u00e4ngerName"
})
public class HeaderType {

    @XmlElement(name = "Empf\u00e4ngerID", required = true)
    protected String empfängerID;
    @XmlElement(name = "Empf\u00e4ngerName", required = true)
    protected String empfängerName;

    /**
     * Gets the value of the empfängerID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmpfängerID() {
        return empfängerID;
    }

    /**
     * Sets the value of the empfängerID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmpfängerID(String value) {
        this.empfängerID = value;
    }

    /**
     * Gets the value of the empfängerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmpfängerName() {
        return empfängerName;
    }

    /**
     * Sets the value of the empfängerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmpfängerName(String value) {
        this.empfängerName = value;
    }

}
